In [73]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('./dataset/adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

1. How many men and women (sex feature) are represented in this dataset?

In [10]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

2. What is the average age (age feature) of women?

In [81]:
data[data['sex']=='Female']['age'].mean() #first solution

data.loc[data['sex']=='Female', 'age'].mean()

36.85823043357163

3. What is the percentage of German citizens (native-country feature)?

In [84]:
data['native-country'].value_counts(normalize=True)['Germany']*100 #Fail first solution

float((data['native-country'] == 'Germany').sum()) / data.shape[0]

0.004207487485028101

4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (salary feature) and those who earn less than 50K per year?

In [86]:
data.groupby('salary')['age'].agg(['mean','std']).round(1)

        mean   std
salary
<=50K   36.8  14.0
>50K    44.2  10.5

6. Is it true that people who earn more than 50K have at least high school education?

In [36]:
data.loc[data['salary'] == '>50K','education'].unique()

array(['HS-grad', 'Masters', 'Bachelors', 'Some-college', 'Assoc-voc',
       'Doctorate', 'Prof-school', 'Assoc-acdm', '7th-8th', '12th',
       '10th', '11th', '9th', '5th-6th', '1st-4th'], dtype=object)

7. Display age statistics for each race (race feature) and each gender (sex feature). Use groupby() and describe(). Find the maximum age of men of Amer-Indian-Eskimo race

In [ ]:
# data.groupby('race')['age'].describe() NOPE

for (race, sex), sub_df in data.groupby(['race','sex']):
    print("Race: {0}, sex: {1}".format(race, sex))
    print(sub_df['age'].describe())

Race: Amer-Indian-Eskimo, sex: Female
count    119.000000
mean      37.117647
std       13.114991
min       17.000000
25%       27.000000
50%       36.000000
75%       46.000000
max       80.000000
Name: age, dtype: float64
Race: Amer-Indian-Eskimo, sex: Male
count    192.000000
mean      37.208333
std       12.049563
min       17.000000
25%       28.000000
50%       35.000000
75%       45.000000
max       82.000000
Name: age, dtype: float64
Race: Asian-Pac-Islander, sex: Female
count    346.000000
mean      35.089595
std       12.300845
min       17.000000
25%       25.000000
50%       33.000000
75%       43.750000
max       75.000000
Name: age, dtype: float64
Race: Asian-Pac-Islander, sex: Male
count    693.000000
mean      39.073593
std       12.883944
min       18.000000
25%       29.000000
50%       37.000000
75%       46.000000
max       90.000000
Name: age, dtype: float64
Race: Black, sex: Female
count    1555.000000
mean       37.854019
std        12.637197
min        17.000000
25%        28.000000
50%        37.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: Black, sex: Male
count    1569.000000
mean       37.682600
std        12.882612
min        17.000000
25%        27.000000
50%        36.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: Other, sex: Female
count    109.000000
mean      31.678899
std       11.631599
min       17.000000
25%       23.000000
50%       29.000000
75%       39.000000
max       74.000000
Name: age, dtype: float64
Race: Other, sex: Male
count    162.000000
mean      34.654321
std       11.355531
min       17.000000
25%       26.000000
50%       32.000000
75%       42.000000
max       77.000000
Name: age, dtype: float64
Race: White, sex: Female
count    8642.000000
mean       36.811618
std        14.329093
min        17.000000
25%        25.000000
50%        35.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: White, sex: Male
count    19174.000000
mean        39.652498
std         13.436029
min         17.000000
25%         29.000000
50%         38.000000
75%         49.000000
max         90.000000
Name: age, dtype: float64

In [45]:
data.groupby(['race','sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men?

In [ ]:
data[data['salary'] == '>50K']['marital-status'].value_counts() #first tentative solution

marital-status
Married-civ-spouse       6692
Never-married             491
Divorced                  463
Widowed                    85
Separated                  66
Married-spouse-absent      34
Married-AF-spouse          10
Name: count, dtype: int64

In [51]:
data.loc[(data['sex'] == 'Male') & (data['marital-status'].isin(['Never-married', 'Separated', 'Divorced','Widowed'])),'salary'].value_counts()

salary
<=50K    7552
>50K      697
Name: count, dtype: int64

In [52]:
data.loc[(data['sex'] == 'Male') & (data['marital-status'].str.startswith('Married')), 'salary'].value_counts()

salary
<=50K    7576
>50K     5965
Name: count, dtype: int64

9. What is the maximum number of hours a person works per week? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?

In [53]:
data['hours-per-week'].describe()

count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

In [ ]:
data.loc[data['hours-per-week'] >= 99, 'salary'].value_counts() #first tentative solution

salary
<=50K    60
>50K     25
Name: count, dtype: int64

In [64]:
max_load = data['hours-per-week'].max()
print("Max time - {0} hours/week".format(max_load))

num_workaholics = data[data['hours-per-week'] == max_load].shape[0]
print("Total number of such hard workers - {0}".format(num_workaholics))

rich_share = float(data[(data['hours-per-week'] == max_load) & (data['salary'] == '>50K')].shape[0]) / num_workaholics
print("Percentuage of rich among them - {0}%".format(int(rich_share * 100)))

Max time - 99 hours/week
Total number of such hard workers - 85
Percentuage of rich among them - 29%

10. Count the average time of work for those who earn a little and a lot (salary) for each country. What will these be for Japan?

In [ ]:
data.groupby(['native-country', 'salary']).describe()['age'] #first tentative solution

                        count       mean        std   min    25%   50%    75%  \
native-country salary
?              <=50K    437.0  36.853547  12.532401  17.0  28.00  35.0  43.00
               >50K     146.0  44.328767  10.158814  22.0  37.00  43.0  51.00
Cambodia       <=50K     12.0  35.666667  12.404789  18.0  27.75  34.5  37.75
               >50K       7.0  41.428571   7.828519  27.0  38.50  42.0  47.00
Canada         <=50K     82.0  41.012195  16.507009  17.0  27.00  38.0  53.00
...                       ...        ...        ...   ...    ...   ...    ...
United-States  >50K    7171.0  44.297169  10.485946  19.0  37.00  44.0  51.00
Vietnam        <=50K     62.0  33.951613  13.724965  19.0  23.00  30.0  43.75
               >50K       5.0  35.400000  11.326959  23.0  30.00  30.0  43.00
Yugoslavia     <=50K     10.0  38.000000  13.072448  20.0  26.50  41.0  44.50
               >50K       6.0  40.166667  13.136463  29.0  35.00  35.5  39.00

                        max
native-country salary
?              <=50K   90.0
               >50K    76.0
Cambodia       <=50K   65.0
               >50K    50.0
Canada         <=50K   80.0
...                     ...
United-States  >50K    90.0
Vietnam        <=50K   73.0
               >50K    51.0
Yugoslavia     <=50K   56.0
               >50K    66.0

[82 rows x 8 columns]

In [ ]:
for (country, salary), sub_df in data.groupby(['native-country', 'salary']): #computer science solutiuon
    print(country, salary, round(sub_df['hours-per-week'].mean(), 2))

? <=50K 40.16
? >50K 45.55
Cambodia <=50K 41.42
Cambodia >50K 40.0
Canada <=50K 37.91
Canada >50K 45.64
China <=50K 37.38
China >50K 38.9
Columbia <=50K 38.68
Columbia >50K 50.0
Cuba <=50K 37.99
Cuba >50K 42.44
Dominican-Republic <=50K 42.34
Dominican-Republic >50K 47.0
Ecuador <=50K 38.04
Ecuador >50K 48.75
El-Salvador <=50K 36.03
El-Salvador >50K 45.0
England <=50K 40.48
England >50K 44.53
France <=50K 41.06
France >50K 50.75
Germany <=50K 39.14
Germany >50K 44.98
Greece <=50K 41.81
Greece >50K 50.62
Guatemala <=50K 39.36
Guatemala >50K 36.67
Haiti <=50K 36.33
Haiti >50K 42.75
Holand-Netherlands <=50K 40.0
Honduras <=50K 34.33
Honduras >50K 60.0
Hong <=50K 39.14
Hong >50K 45.0
Hungary <=50K 31.3
Hungary >50K 50.0
India <=50K 38.23
India >50K 46.48
Iran <=50K 41.44
Iran >50K 47.5
Ireland <=50K 40.95
Ireland >50K 48.0
Italy <=50K 39.62
Italy >50K 45.4
Jamaica <=50K 38.24
Jamaica >50K 41.1
Japan <=50K 41.0
Japan >50K 47.96
Laos <=50K 40.38
Laos >50K 40.0
Mexico <=50K 40.0
Mexico >50K 46.58
Nicaragua <=50K 36.09
Nicaragua >50K 37.5
Outlying-US(Guam-USVI-etc) <=50K 41.86
Peru <=50K 35.07
Peru >50K 40.0
Philippines <=50K 38.07
Philippines >50K 43.03
Poland <=50K 38.17
Poland >50K 39.0
Portugal <=50K 41.94
Portugal >50K 41.5
Puerto-Rico <=50K 38.47
Puerto-Rico >50K 39.42
Scotland <=50K 39.44
Scotland >50K 46.67
South <=50K 40.16
South >50K 51.44
Taiwan <=50K 33.77
Taiwan >50K 46.8
Thailand <=50K 42.87
Thailand >50K 58.33
Trinadad&Tobago <=50K 37.06
Trinadad&Tobago >50K 40.0
United-States <=50K 38.8
United-States >50K 45.51
Vietnam <=50K 37.19
Vietnam >50K 39.2
Yugoslavia <=50K 41.6
Yugoslavia >50K 49.5

In [80]:
pd.crosstab(data['native-country'], data['salary'], values=data['hours-per-week'], aggfunc=np.mean).T.round(2) #elagant solution

/tmp/ipykernel_2610/3669700682.py:1: FutureWarning: The provided callable <function mean at 0x7e98fc046560> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'mean' instead.
  pd.crosstab(data['native-country'], data['salary'], values=data['hours-per-week'], aggfunc=np.mean).T.round(2) #elagant solution

native-country,?,Cambodia,Canada,China,Columbia,Cuba,Dominican-Republic,Ecuador,El-Salvador,England,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
salary,,,,,,,,,,,,,,,,,,,,,
<=50K,40.16,41.42,37.91,37.38,38.68,37.99,42.34,38.04,36.03,40.48,...,41.94,38.47,39.44,40.16,33.77,42.87,37.06,38.80,37.19,41.6
>50K,45.55,40.00,45.64,38.90,50.00,42.44,47.00,48.75,45.00,44.53,...,41.50,39.42,46.67,51.44,46.80,58.33,40.00,45.51,39.20,49.5