## Titatic survival

In [2]:
import pandas as pd
df = pd.read_csv('./ML_dataset/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
1,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
2,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
3,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
4,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age      Fare
0         1       3  female  35.0   20.2500
1         1       2  female  28.0   24.0000
2         0       3  female  40.0    9.4750
3         1       3  female  18.0    9.3500
4         1       1  female  29.0  211.3375

In [5]:
target = df.Survived
inputs = df.drop('Survived', axis='columns')

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0    True  False
1    True  False
2    True  False
3    True  False
4    True  False

In [7]:
inputs = pd.concat([inputs, dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age      Fare  female   male
0       3  female  35.0   20.2500    True  False
1       2  female  28.0   24.0000    True  False
2       3  female  40.0    9.4750    True  False
3       3  female  18.0    9.3500    True  False
4       1  female  29.0  211.3375    True  False

In [8]:
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head()

   Pclass   Age      Fare  female   male
0       3  35.0   20.2500    True  False
1       2  28.0   24.0000    True  False
2       3  40.0    9.4750    True  False
3       3  18.0    9.3500    True  False
4       1  29.0  211.3375    True  False

In [9]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [10]:
inputs.Age[:10]

0    35.0
1    28.0
2    40.0
3    18.0
4    29.0
5     2.0
6    25.0
7    19.0
8     6.0
9     2.0
Name: Age, dtype: float64

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age      Fare  female   male
0       3  35.0   20.2500    True  False
1       2  28.0   24.0000    True  False
2       3  40.0    9.4750    True  False
3       3  18.0    9.3500    True  False
4       1  29.0  211.3375    True  False

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)

In [14]:
len(X_train)

712

In [15]:
len(X_test)

179

In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
import joblib
joblib.dump(model, 'naive_model')

['naive_model']

In [20]:
model = joblib.load('naive_model')

In [21]:
model.fit(X_train, y_train)

GaussianNB()

In [22]:
model.score(X_test, y_test)

0.8268156424581006

In [23]:
model.predict(X_test)

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1])

## Email Spam filter

In [2]:
import pandas as pd
df = pd.read_csv('./ML_dataset/spam.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2, random_state=42)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [8]:
import joblib
joblib.dump(model, 'naive_spam')

['naive_spam']

In [ ]:
model = joblib.load('naive_spam')

In [11]:
model.fit(X_train_count, y_train)

MultinomialNB()

In [12]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exlusive offer just for you. DOnt miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [13]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9919282511210762