## Titatic survival

In [1]:
import pandas as pd
df = pd.read_csv('./ML_dataset/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
1,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
2,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
3,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
4,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S

In [2]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age      Fare
0         1       3  female  35.0   20.2500
1         1       2  female  28.0   24.0000
2         0       3  female  40.0    9.4750
3         1       3  female  18.0    9.3500
4         1       1  female  29.0  211.3375

In [3]:
target = df.Survived
inputs = df.drop('Survived', axis='columns')

In [4]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0    True  False
1    True  False
2    True  False
3    True  False
4    True  False

In [5]:
inputs = pd.concat([inputs, dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age      Fare  female   male
0       3  female  35.0   20.2500    True  False
1       2  female  28.0   24.0000    True  False
2       3  female  40.0    9.4750    True  False
3       3  female  18.0    9.3500    True  False
4       1  female  29.0  211.3375    True  False

In [6]:
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head()

   Pclass   Age      Fare  female   male
0       3  35.0   20.2500    True  False
1       2  28.0   24.0000    True  False
2       3  40.0    9.4750    True  False
3       3  18.0    9.3500    True  False
4       1  29.0  211.3375    True  False

In [7]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [8]:
inputs.Age[:10]

0    35.0
1    28.0
2    40.0
3    18.0
4    29.0
5     2.0
6    25.0
7    19.0
8     6.0
9     2.0
Name: Age, dtype: float64

In [9]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age      Fare  female   male
0       3  35.0   20.2500    True  False
1       2  28.0   24.0000    True  False
2       3  40.0    9.4750    True  False
3       3  18.0    9.3500    True  False
4       1  29.0  211.3375    True  False

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)

In [11]:
len(X_train)

712

In [12]:
len(X_test)

179

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
import joblib
joblib.dump(model, 'naive_model')

['naive_model']

In [14]:
model = joblib.load('naive_model')

In [15]:
model.fit(X_train, y_train)

GaussianNB()

In [16]:
model.score(X_test, y_test)

0.8268156424581006

In [17]:
model.predict(X_test)

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1])

## Email Spam filter

In [18]:
import pandas as pd
df = pd.read_csv('./ML_dataset/spam.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [19]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [20]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2, random_state=42)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [24]:
import joblib
joblib.dump(model, 'naive_spam')

['naive_spam']

In [25]:
model = joblib.load('naive_spam')

In [26]:
model.fit(X_train_count, y_train)

MultinomialNB()

In [27]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exlusive offer just for you. DOnt miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [28]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9919282511210762

In [29]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [30]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [31]:
clf.score(X_test, y_test)

0.9919282511210762


---

## Exercise

Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data

In [32]:
from sklearn.datasets import load_wine

wine = load_wine()

In [33]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [69]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [55]:
df['target'] = wine.target
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [44]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']

In [49]:
len(wine.data)

178

In [50]:
len(wine.target)

178

In [56]:
# from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['target'], axis='columns'), wine.target, test_size=0.2, random_state=42)

In [57]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [58]:
model.fit(X_train, y_train)

GaussianNB()

In [65]:
sc1 = model.score(X_test, y_test)

In [60]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()

In [61]:
model2.fit(X_train, y_train)

MultinomialNB()

In [66]:
sc2 = model2.score(X_test, y_test)

In [68]:
print(f"Best Naive Bayes model for wine dataset is: {model if sc1 > sc2 else model2}")

Best Naive Bayes model for wine dataset is: GaussianNB()